### ISSUE TITLE
Tests currently broken

### ISSUE THREAD

**Issue by esc** [Blosc/bloscpack#62]
```
\Traceback (most recent call last):
  File "/home/esc/git/bloscpack/test-venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/esc/git/bloscpack/test/test_headers.py", line 168, in test_decode_blosc_header
    nt.assert_equal(expected, header)
AssertionError: {'flags': 3, 'blocksize': 88, 'typesize':[58 chars] 108} != OrderedDict([('version', 2), ('versionlz'[86 chars]08)])
```

On master.

**Comment by FrancescElies** [comment]
It seems like blosckpack works well with python-blosc 1.4.1 https://travis-ci.org/FrancescElies/bloscpack/builds/243365299 but beyond that it fails.
Shall we set the requirements to that version?

**Comment by FrancescElies** [comment]
In the failing test we get flag = 19 (0x13).

According to [header description](https://github.com/Blosc/c-blosc/blob/master/README_HEADER.rst) 0x13 sets following bits.

bit 0 (0x01):	Whether the byte-shuffle filter has been applied or not.
bit 1 (0x02):	Whether the internal buffer is a pure memcpy or not.
bit 4 (0x10):	If set, the blocks will not be split in sub-blocks during compression.

In my opinion Bit 0 seems fine, shuffle was activated on the test, Last three bits are 0 which means blosclz was used, this is also ok. The only difference seems to be bit 4 which seems to be a default now, right?
 

```
In [1]: expected
Out[1]: 
{'blocksize': 88,
 'ctbytes': 108,
 'flags': 3,
 'nbytes': 92,
 'typesize': 8,
 'version': 2,
 'versionlz': 1}

In [2]: header
Out[2]: 
OrderedDict([('version', 2),
             ('versionlz', 1),
             ('flags', 19),
             ('typesize', 8),
             ('nbytes', 92),
             ('blocksize', 88),
             ('ctbytes', 108)])

In [3]: hex(19)
Out[3]: '0x13'

In [4]: blosc_args
Out[4]: BloscArgs(typesize=8, clevel=7, shuffle=True, cname='blosclz')

```

**Comment by FrancescElies** [comment]
The comit that made the test fail was https://github.com/Blosc/python-blosc/commit/1713e78

**Comment by FrancescElies** [comment]
Actually the newly introduced don't split `*(context->header_flags) |= dont_split << 4;  /* dont_split is in bit 4 */` is setting that bit

**Comment by FrancescElies** [comment]
This bit is set for `BLOSC_BLOSCLZ`, so the test would be fine if we update the value of the flag to 0x13, what do you think?

**Comment by FrancescAlted** [comment]
Yes, I introduced this change in the Blosc header so as to accommodate larger blocks for LZ4, LZ4HC, Zlib and Zstd (they seem happier when compressing large blocks, but not BloscLZ or Snappy).  This is a totally backward compatible and completely safe, so I don't think finding it set would be any problem.

**Comment by esc** [comment]
I agree

**Comment by esc** [comment]
With which version of `python-blosc` was this introduced?

**Comment by esc** [comment]
Also, we should update the documentation in the `README` since this contains documentation about the blosc header.

**Comment by FrancescAlted** [comment]
1.4.3 I think.

**Comment by esc** [comment]
I did a grep for `flags`:

```
README.rst:      |   |   +------flags
bloscpack/headers.py:                        ('flags', decode_uint8(buffer_[2])),
bloscpack/numpy_io.py:        if numpy.isfortran(ndarray) and not ndarray.flags['F_CONTIGUOUS']:
bloscpack/numpy_io.py:        elif not numpy.isfortran(ndarray) and not ndarray.flags['C_CONTIGUOUS']:
test/test_append.py:    # crank up the clevel to ensure compression happens, otherwise the flags
test/test_append.py:    nt.assert_equal(blosc_header_zero['flags'], 1)
test/test_append.py:    nt.assert_equal(blosc_header_last['flags'], 0)
test/test_file_io.py:                        'flags':     1,
test/test_headers.py:                'flags': 1,
test/test_headers.py:                'flags': 0,  # no shuffle flag
test/test_headers.py:                'flags': 3,  # 1 for shuffle 2 for non-compressed
test/test_numpy_io.py:        yield nt.assert_equal, blosc_header['flags'] >> 5, int_id
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 52428800\), \('blocksize', [1-9]\d*\), \('ctbytes', [1-9]\d*\)\]\) (re)
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 52428800\), \('blocksize', [1-9]\d*\), \('ctbytes', [1-9]\d*\)\]\) (re)
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 52428800\), \('blocksize', [1-9]\d*\), \('ctbytes', [1-9]\d*\)\]\) (re)
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 2713600\), \('blocksize', [1-9]\d*\), \('ctbytes', [1-9]\d*\)\]\) (re)
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 52428800\), \('blocksize', 131072\), \('ctbytes', [1-9]\d*\)\]\) (re)
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 52428800\), \('blocksize', 131072\), \('ctbytes', [1-9]\d*\)\]\) (re)
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 52428800\), \('blocksize', 131072\), \('ctbytes', [1-9]\d*\)\]\) (re)
test_cmdline/test_verbose_debug.cram:  blpk: blosc_header: OrderedDict\(\[\('version', 2\), \('versionlz', 1\), \('flags', 1\), \('typesize', 8\), \('nbytes', 2713600\), \('blocksize', 131072\), \('ctbytes', [1-9]\d*\)\]\) (re)
```

I don't think they are used much, so probably just adapting the test will suffice. The test suite is pretty tight, but who knows.

**Comment by esc** [comment]
When exactly does bit 4 get set?

**Comment by esc** [comment]
Because if it is simply set whenever BloscLZ is used, then the two tests above should fail too.

https://github.com/Blosc/bloscpack/blob/master/test/test_headers.py#L129

This is is also the result of the buffer not being compressible:

https://github.com/Blosc/bloscpack/blob/master/test/test_headers.py#L155

Or did I miss something?

**Comment by esc** [comment]
Is perhaps the following condition being triggered:

https://github.com/Blosc/python-blosc/commit/1713e78#diff-3dfe2ac6bc1e9903583bf8bfd2c712e3R1044

**Comment by FrancescElies** [comment]
Right! that condition is being triggered due to smaller `blocksize`
I printed the values of the vars of interest, see below.

  ```
  # basic test case
  => (compcode == BLOSC_BLOSCLZ)              = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1040]
  => (compcode == BLOSC_SNAPPY)               = 0 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1042]
  => (typesize <= MAX_SPLITS)                 = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1043]
  => (blocksize / typesize) >= MIN_BUFFERSIZE = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1044]
  => blocksize                                = 131072 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1044]
  => typesize                                 = 8 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1045]
  => MIN_BUFFERSIZE                           = 128 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1046]
  => split_block(context->compcode, context->typesize, context->blocksize) = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1143]
  => dont_split                                                            = 0 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1145]

  # deactivate shuffle 
  =================================================================================> 
  /python-blosc/c-blosc/blosc/blosc.c Line 1040]                                                                                       
  => (compcode == BLOSC_BLOSCLZ)              = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1040]
  => (compcode == BLOSC_SNAPPY)               = 0 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1042]
  => (typesize <= MAX_SPLITS)                 = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1043]
  => (blocksize / typesize) >= MIN_BUFFERSIZE = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1044]
  => blocksize                                = 16000 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1044]
  => typesize                                 = 8 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1045]
  => MIN_BUFFERSIZE                           = 128 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1046]
  => split_block(context->compcode, context->typesize, context->blocksize) = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1143]
  => dont_split                                                            = 0 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1145]

  # uncompressible data
  =================================================================================> 
  /python-blosc/c-blosc/blosc/blosc.c Line 1040]                                                                                       
  => (compcode == BLOSC_BLOSCLZ)              = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1040]
  => (compcode == BLOSC_SNAPPY)               = 0 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1042]
  => (typesize <= MAX_SPLITS)                 = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1043]
  => (blocksize / typesize) >= MIN_BUFFERSIZE = 0 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1044]
  => blocksize                                = 88 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1044]
  => typesize                                 = 8 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1045]
  => MIN_BUFFERSIZE                           = 128 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1046]
  => split_block(context->compcode, context->typesize, context->blocksize) = 0 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1143]
  => dont_split                                                            = 1 [~/src/python-blosc/c-blosc/blosc/blosc.c Line 1145]
  ### header ~/src/bloscpack/test/test_headers.py Line 175
  OrderedDict([('version', 2), ('versionlz', 1), ('flags', 19), ('typesize', 8), ('nbytes', 92), ('blocksize', 88), ('ctbytes', 108)])
  FAIL

  ```
