### ISSUE TITLE
Value error when compressing file

### ISSUE THREAD

**Issue by eduardosm** [Blosc/bloscpack#80]
```
Traceback (most recent call last):
  File "/bin/blpk", line 11, in <module>
    load_entry_point('bloscpack==0.14.0', 'console_scripts', 'blpk')()
  File "/usr/lib/python3.7/site-packages/bloscpack/cli.py", line 460, in main
    metadata_args=MetadataArgs())
  File "/usr/lib/python3.7/site-packages/bloscpack/file_io.py", line 464, in pack_file
    metadata_args=metadata_args)
  File "/usr/lib/python3.7/site-packages/bloscpack/abstract_io.py", line 153, in pack
    max_app_chunks=max_app_chunks
  File "/usr/lib/python3.7/site-packages/bloscpack/headers.py", line 295, in __init__
    % (last_chunk, chunk_size))
ValueError: 'last_chunk' (854860) is larger than 'chunk_size' (854856)
```

When trying to compress the following file: [test.zip](https://github.com/Blosc/bloscpack/files/2521659/test.zip)

blosc 1.14.4
python-blosc 1.6.1
bloscpack 0.14.0

**Comment by esc** [comment]
Can you try #81 please?

**Comment by eduardosm** [comment]
Tested, it seems to work without issues
